// components/project-management/mock-data.ts

import { Project, ProjectStatus, Priority, Task, TaskStatus } from './enums';

const MOCK_USER_ID = 'user_123'; // A placeholder user ID

export const mockProjects: Project[] = [
    {
        id: 'proj_1',
        name: 'Develop Next.js App',
        description: 'Build a comprehensive daily check-in and project management application using Next.js, Shadcn UI, and Prisma.',
        color: '#FF6B6B', // Red
        status: ProjectStatus.ACTIVE,
        priority: Priority.URGENT,
        startDate: new Date('2024-08-01'),
        dueDate: new Date('2024-10-31'),
        completedAt: null,
        progress: 75, // Will be dynamically calculated based on tasks
        userId: MOCK_USER_ID,
        categoryId: 'cat_webdev',
        parentId: null,
        createdAt: new Date('2024-07-25'),
        updatedAt: new Date('2024-09-01'),
    },
    {
        id: 'proj_2',
        name: 'Learn Rust Programming',
        description: 'Deep dive into Rust language fundamentals, ownership, borrowing, and concurrency.',
        color: '#4ECDC4', // Teal
        status: ProjectStatus.ON_HOLD,
        priority: Priority.MEDIUM,
        startDate: new Date('2024-09-15'),
        dueDate: new Date('2025-03-15'),
        completedAt: null,
        progress: 10,
        userId: MOCK_USER_ID,
        categoryId: 'cat_learning',
        parentId: null,
        createdAt: new Date('2024-09-01'),
        updatedAt: new Date('2024-09-05'),
    },
    {
        id: 'proj_3',
        name: 'Plan Vacation to Japan',
        description: 'Research destinations, book flights and accommodation, create itinerary for a 2-week trip.',
        color: '#45B7D1', // Blue
        status: ProjectStatus.ACTIVE,
        priority: Priority.HIGH,
        startDate: new Date('2024-09-01'),
        dueDate: new Date('2024-11-30'),
        completedAt: null,
        progress: 40,
        userId: MOCK_USER_ID,
        categoryId: 'cat_personal',
        parentId: null,
        createdAt: new Date('2024-08-20'),
        updatedAt: new Date('2024-09-03'),
    },
    {
        id: 'proj_4',
        name: 'Write Blog Post on AI',
        description: 'Draft, edit, and publish a blog post about recent advancements in AI and their implications.',
        color: '#FED766', // Yellow
        status: ProjectStatus.COMPLETED,
        priority: Priority.LOW,
        startDate: new Date('2024-07-01'),
        dueDate: new Date('2024-07-31'),
        completedAt: new Date('2024-07-28'),
        progress: 100,
        userId: MOCK_USER_ID,
        categoryId: 'cat_content',
        parentId: null,
        createdAt: new Date('2024-06-20'),
        updatedAt: new Date('2024-07-28'),
    },
    {
        id: 'proj_5',
        name: 'Refactor Authentication Module',
        description: 'Improve the security and maintainability of the authentication system in the main application.',
        color: '#A7D7C5', // Light Green
        status: ProjectStatus.ACTIVE,
        priority: Priority.HIGH,
        startDate: new Date('2024-09-01'),
        dueDate: new Date('2024-09-20'),
        completedAt: null,
        progress: 60,
        userId: MOCK_USER_ID,
        categoryId: 'cat_webdev',
        parentId: null,
        createdAt: new Date('2024-08-25'),
        updatedAt: new Date('2024-09-04'),
    },
];

export const mockTasks: Task[] = [
    // Tasks for 'Develop Next.js App' (proj_1)
    {
        id: 'task_1_1',
        title: 'Set up Next.js project structure',
        description: 'Initialize project, configure Tailwind CSS and Shadcn UI.',
        status: TaskStatus.COMPLETED,
        priority: Priority.HIGH,
        dueDate: new Date('2024-08-05'),
        completedAt: new Date('2024-08-04'),
        estimatedMinutes: 180,
        actualMinutes: 150,
        projectId: 'proj_1',
        categoryId: null,
        parentId: null,
        createdAt: new Date('2024-08-01'),
        updatedAt: new Date('2024-08-04'),
    },
    {
        id: 'task_1_2',
        title: 'Implement Project Management UI',
        description: 'Create components for project list, details, and forms.',
        status: TaskStatus.IN_PROGRESS,
        priority: Priority.URGENT,
        dueDate: new Date('2024-09-10'),
        completedAt: null,
        estimatedMinutes: 480,
        actualMinutes: 300,
        projectId: 'proj_1',
        categoryId: null,
        parentId: null,
        createdAt: new Date('2024-08-06'),
        updatedAt: new Date('2024-09-05'),
    },
    {
        id: 'task_1_3',
        title: 'Integrate Prisma with Supabase',
        description: 'Set up database schema, generate Prisma client, and connect to Supabase.',
        status: TaskStatus.TODO,
        priority: Priority.HIGH,
        dueDate: new Date('2024-09-20'),
        completedAt: null,
        estimatedMinutes: 360,
        actualMinutes: null,
        projectId: 'proj_1',
        categoryId: null,
        parentId: null,
        createdAt: new Date('2024-08-10'),
        updatedAt: new Date('2024-09-01'),
    },
    {
        id: 'task_1_4',
        title: 'Develop API endpoints for projects',
        description: 'Create RESTful APIs for CRUD operations on projects.',
        status: TaskStatus.TODO,
        priority: Priority.MEDIUM,
        dueDate: new Date('2024-09-25'),
        completedAt: null,
        estimatedMinutes: 240,
        actualMinutes: null,
        projectId: 'proj_1',
        categoryId: null,
        parentId: null,
        createdAt: new Date('2024-08-15'),
        updatedAt: new Date('2024-09-01'),
    },
    // Tasks for 'Learn Rust Programming' (proj_2)
    {
        id: 'task_2_1',
        title: 'Complete Rust Book Chapter 1-3',
        description: 'Read and understand basic syntax, variables, and functions.',
        status: TaskStatus.IN_PROGRESS,
        priority: Priority.MEDIUM,
        dueDate: new Date('2024-09-30'),
        completedAt: null,
        estimatedMinutes: 120,
        actualMinutes: 60,
        projectId: 'proj_2',
        categoryId: null,
        parentId: null,
        createdAt: new Date('2024-09-15'),
        updatedAt: new Date('2024-09-18'),
    },
    // Tasks for 'Plan Vacation to Japan' (proj_3)
    {
        id: 'task_3_1',
        title: 'Research flight options',
        description: 'Compare prices and routes for flights to Tokyo.',
        status: TaskStatus.COMPLETED,
        priority: Priority.HIGH,
        dueDate: new Date('2024-09-10'),
        completedAt: new Date('2024-09-08'),
        estimatedMinutes: 90,
        actualMinutes: 75,
        projectId: 'proj_3',
        categoryId: null,
        parentId: null,
        createdAt: new Date('2024-09-01'),
        updatedAt: new Date('2024-09-08'),
    },
    {
        id: 'task_3_2',
        title: 'Book accommodation in Kyoto',
        description: 'Find and reserve a hotel or Airbnb for 5 nights.',
        status: TaskStatus.TODO,
        priority: Priority.HIGH,
        dueDate: new Date('2024-09-25'),
        completedAt: null,
        estimatedMinutes: 180,
        actualMinutes: null,
        projectId: 'proj_3',
        categoryId: null,
        parentId: null,
        createdAt: new Date('2024-09-05'),
        updatedAt: new Date('2024-09-05'),
    },
    // Tasks for 'Refactor Authentication Module' (proj_5)
    {
        id: 'task_5_1',
        title: 'Review current authentication flow',
        description: 'Analyze existing code for vulnerabilities and areas of improvement.',
        status: TaskStatus.COMPLETED,
        priority: Priority.HIGH,
        dueDate: new Date('2024-09-03'),
        completedAt: new Date('2024-09-02'),
        estimatedMinutes: 120,
        actualMinutes: 100,
        projectId: 'proj_5',
        categoryId: null,
        parentId: null,
        createdAt: new Date('2024-09-01'),
        updatedAt: new Date('2024-09-02'),
    },
    {
        id: 'task_5_2',
        title: 'Implement JWT refresh token mechanism',
        description: 'Add support for secure refresh tokens to improve session management.',
        status: TaskStatus.IN_PROGRESS,
        priority: Priority.URGENT,
        dueDate: new Date('2024-09-15'),
        completedAt: null,
        estimatedMinutes: 300,
        actualMinutes: 180,
        projectId: 'proj_5',
        categoryId: null,
        parentId: null,
        createdAt: new Date('2024-09-03'),
        updatedAt: new Date('2024-09-05'),
    },
];
