import type { Metadata } from "next";
import "./globals.css";

import ProvidersWrapper from "@/components/providers/ProvidersWrapper";
import { ThemeProvider } from "@/components/providers/ThemeProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ProvidersWrapper>
        {children}
        </ProvidersWrapper>
      </body>
    </html>
  );
}
